# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86649290186fc2ca6d429bea5e5ac051e6d9bd5df6642f1c97e0a3f802e9708dc5b1e3063f26eea8f363c68397a4d96a96365d67368d3754c299bb586ea59d41

test:
  secret_key_base: 34f414996a4f017214f2691c3cd253924e499e83fc3bf205287f96774d027afa0abfae2fb7dc95df61832c90f66d35061914a4505d02aac2591ea807bc8e569d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
